name: train-mlops-environment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pip
  - py-cpuinfo=5.0.0
  - joblib=1.2.0
  - setuptools-git
  - 'psutil>5.0.0,<6.0.0'
  - tqdm
  - numpy
  - pandas
  - openssl
  - pip:
    - azureml-core==1.60.0
    - azureml-mlflow==1.60.0
    - azureml-pipeline-core==1.60.0
    - azureml-telemetry==1.60.0
    - azureml-interpret==1.60.0
    - azureml-responsibleai==1.60.0
    - azureml-automl-core==1.60.0
    - azureml-automl-runtime==1.60.0
    - azureml-train-automl-client==1.60.0
    - azureml-train-automl-runtime==1.60.0
    - azureml-train-automl==1.60.0
    - azureml-dataset-runtime==1.60.0
    - azureml-defaults==1.60.0
    - mlflow-skinny==2.15.1
    - xgboost==1.5.2
    - prophet==1.1.4
    - inference-schema
    - mltable>=1.0.0
    - azure-identity
    - azure-ai-ml
    - azureml-inference-server-http==1.4.1
    - pyarrow==14.0.2  
    - pytorch=2.2.2
