# VPN Certificate Generation Script for Azure Point-to-Site VPN
# This script generates self-signed certificates for Azure P2S VPN authentication

Write-Host "=== Azure ML Hub VPN Certificate Generation ===" -ForegroundColor Green
Write-Host "This script will generate certificates for Point-to-Site VPN access" -ForegroundColor Yellow
Write-Host ""

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
if (-not $isAdmin) {
    Write-Warning "This script should be run as Administrator for proper certificate installation."
    $continue = Read-Host "Continue anyway? (y/N)"
    if ($continue -ne 'y' -and $continue -ne 'Y') {
        exit 1
    }
}

try {
    # Set certificate names
    $rootCertName = "AzureMLHubVPNRootCert"
    $clientCertName = "AzureMLHubVPNClientCert"
    
    Write-Host "Step 1: Creating root certificate..." -ForegroundColor Cyan
    
    # Create root certificate
    $rootCert = New-SelfSignedCertificate -Type Custom -KeySpec Signature `
        -Subject "CN=$rootCertName" -KeyExportPolicy Exportable `
        -HashAlgorithm sha256 -KeyLength 2048 `
        -CertStoreLocation "Cert:\CurrentUser\My" `
        -KeyUsageProperty Sign -KeyUsage CertSign
    
    Write-Host "✓ Root certificate created: $($rootCert.Thumbprint)" -ForegroundColor Green
    
    Write-Host "Step 2: Creating client certificate..." -ForegroundColor Cyan
    
    # Create client certificate signed by root certificate
    $clientCert = New-SelfSignedCertificate -Type Custom -DnsName P2SChildCert `
        -KeySpec Signature -Subject "CN=$clientCertName" -KeyExportPolicy Exportable `
        -HashAlgorithm sha256 -KeyLength 2048 `
        -CertStoreLocation "Cert:\CurrentUser\My" `
        -Signer $rootCert -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.2")
    
    Write-Host "✓ Client certificate created: $($clientCert.Thumbprint)" -ForegroundColor Green
    
    Write-Host "Step 3: Exporting certificates..." -ForegroundColor Cyan
    
    # Export root certificate (public key only, for Azure)
    $rootCertPath = ".\AzureMLHubVPNRootCert.cer"
    Export-Certificate -Cert $rootCert -FilePath $rootCertPath -Type CERT | Out-Null
    Write-Host "✓ Root certificate exported to: $rootCertPath" -ForegroundColor Green
    
    # Export client certificate with private key (for client installation)
    $clientCertPath = ".\AzureMLHubVPNClientCert.pfx"
    $clientPassword = ConvertTo-SecureString -String "AzureML2025!" -Force -AsPlainText
    Export-PfxCertificate -Cert $clientCert -FilePath $clientCertPath -Password $clientPassword | Out-Null
    Write-Host "✓ Client certificate exported to: $clientCertPath" -ForegroundColor Green
    Write-Host "  Password: AzureML2025!" -ForegroundColor Yellow
    
    Write-Host "Step 4: Generating certificate data for Terraform..." -ForegroundColor Cyan
    
    # Get the root certificate data for Azure (base64 encoded, no headers)
    $rootCertData = [System.Convert]::ToBase64String($rootCert.RawData)
    
    # Create terraform.tfvars content
    $tfvarsContent = @"
# Azure ML Platform Configuration
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

subscription_id = "5784b6a5-de3f-4fa4-8b8f-e5bb70ff6b25"
prefix = "aml"
location = "canadacentral"
location_code = "cc"

# VPN Certificate Data (generated by generate_vpn_certificates.ps1)
vpn_root_certificate_data = "$rootCertData"

# User role assignment
assign_user_roles = true

# Resource tagging
tags = {
  project     = "ml-platform"
  created_by  = "terraform"
  owner       = "ml-team"
  environment = "multi-env"
  deployment  = "hub-spoke-vpn"
}
"@
    
    # Write terraform.tfvars file
    $tfvarsPath = ".\terraform.tfvars"
    $tfvarsContent | Out-File -FilePath $tfvarsPath -Encoding UTF8
    Write-Host "✓ Terraform variables written to: $tfvarsPath" -ForegroundColor Green
    
    Write-Host ""
    Write-Host "=== Certificate Generation Complete! ===" -ForegroundColor Green
    Write-Host ""
    Write-Host "Generated Files:" -ForegroundColor Yellow
    Write-Host "  • $rootCertPath - Root certificate (for Azure VPN Gateway)"
    Write-Host "  • $clientCertPath - Client certificate (install on your machine)"
    Write-Host "  • $tfvarsPath - Terraform variables with certificate data"
    Write-Host ""
    Write-Host "Next Steps:" -ForegroundColor Yellow
    Write-Host "  1. Run: terraform init"
    Write-Host "  2. Run: terraform plan"
    Write-Host "  3. Run: terraform apply"
    Write-Host "  4. After deployment, install the client certificate:"
    Write-Host "     - Double-click: $clientCertPath"
    Write-Host "     - Password: AzureML2025!"
    Write-Host "     - Install to: Current User > Personal"
    Write-Host "  5. Download VPN client from Azure Portal"
    Write-Host ""
    Write-Host "Certificate Details:" -ForegroundColor Cyan
    Write-Host "  Root Certificate Thumbprint: $($rootCert.Thumbprint)"
    Write-Host "  Client Certificate Thumbprint: $($clientCert.Thumbprint)"
    Write-Host "  Certificate Store: Cert:\CurrentUser\My"
    
}
catch {
    Write-Error "Certificate generation failed: $($_.Exception.Message)"
    Write-Host "Common solutions:" -ForegroundColor Yellow
    Write-Host "  • Run PowerShell as Administrator"
    Write-Host "  • Ensure you have permission to create certificates"
    Write-Host "  • Check if antivirus is blocking certificate creation"
    exit 1
}

Write-Host ""
Write-Host "Certificate generation completed successfully!" -ForegroundColor Green
