name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=24.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - pip:
    - azureml-defaults==1.60.0
    - inference-schema[numpy-support]
    - azureml-inference-server-http==1.5.0
    - joblib==1.5.2
    - pandas>=1.3.0
    - azureml-ai-monitoring~=0.1.0b1
    - azure-storage-blob==12.26.0
    - azure-identity==1.25.0
    - numpy