name: mlops-azureml-notebook
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.5
  - pip=25.1
  - numpy=2.3.1
  - pandas=2.3.1
  - matplotlib=3.10.3
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - jupyterlab
  - ipykernel=6.30.0
  - pip:
      - azure-ai-ml==1.28.1
      - azure-identity==1.24.0b1
      - azureml-mlflow==1.60.0.post1
      - mlflow==2.22.1
      - matplotlib-inline==0.1.7
      - opentelemetry-api==1.31.1
      - opentelemetry-sdk==1.31.1
      - opentelemetry-instrumentation==0.52b1
      - opentelemetry-instrumentation-requests==0.52b1
      - pyarrow==19.0.1
      - python-dotenv==1.1.1
      - requests==2.32.4
      - tqdm==4.67.1
