$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: nyc-taxi-compare-integration
description: >-
  Integration validation pipeline that runs training and CompareTaxiFare gate only.
  Used by CI to validate src changes before promoting models to the dev registry.

inputs:
  environment: 'dev'
  model_base: 'taxi-class'
  artifact_id: 'm'
  automl_compute: 'aml-cluster-dev-cc01'
  automl_max_trials: 1
  enable_vote_ensemble: false
  enable_stack_ensemble: false
  conda_file: custom_dev.yaml
  registry: 'mlrdevcc01'
outputs:
  pipeline_job_trained_model:
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount
  pipeline_job_comparison:
    mode: rw_mount
  register_metadata:
    mode: upload

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:aml-cluster-dev-cc01
  continue_on_step_failure: false

jobs:
  merge_job:
    type: command
    code: ../src/merge_data
    command: >-
      python merge_data.py
      --raw_data_green ${{inputs.raw_data_green}}
      --raw_data_yellow ${{inputs.raw_data_yellow}}
      --merged_data ${{outputs.merged_data}}
    inputs:
      raw_data_green:
        type: uri_file
        path: ../data/taxi-data/raw/greenTaxiData.csv
      raw_data_yellow:
        type: uri_file
        path: ../data/taxi-data/raw/yellowTaxiData.csv
    outputs:
      merged_data:
        mode: upload
    environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest

  transform_job:
    type: command
    component: ../src/components/transform.yaml
    inputs:
      test_split_ratio: 0.3
      clean_data: ${{parent.jobs.merge_job.outputs.merged_data}}
    outputs:
      train_data:
      test_data:

  train_job:
    type: command
    component: ../src/components/train.yaml
    inputs:
      training_data: ${{parent.jobs.transform_job.outputs.train_data}}
      testing_data: ${{parent.jobs.transform_job.outputs.test_data}}
      model_name: '${{parent.inputs.model_base}}-${{parent.inputs.environment}}'
      automl_compute: ${{parent.inputs.automl_compute}}
      max_automl_trials: ${{parent.inputs.automl_max_trials}}
      enable_vote_ensemble: ${{parent.inputs.enable_vote_ensemble}}
      enable_stack_ensemble: ${{parent.inputs.enable_stack_ensemble}}
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}

  predict_job:
    type: command
    component: ../src/components/predict.yaml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
      test_data: ${{parent.jobs.transform_job.outputs.test_data}}
    outputs:
      predictions: ${{parent.outputs.pipeline_job_predictions}}

  compare_job:
    type: command
    component: ../src/components/compare.yaml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
      test_data: ${{parent.jobs.transform_job.outputs.test_data}}
      predictions: ${{parent.jobs.predict_job.outputs.predictions}}
      model_name: '${{parent.inputs.model_base}}-${{parent.inputs.environment}}'
    outputs:
      compare_output: ${{parent.outputs.pipeline_job_comparison}}

  register_job:
    type: command
    component: ../src/components/register.yaml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
      model_name: '${{parent.inputs.model_base}}-${{parent.inputs.environment}}-${{parent.inputs.artifact_id}}'
      compare_output: ${{parent.jobs.compare_job.outputs.compare_output}}
      registry: ${{parent.inputs.registry}}
    outputs:
      register_output: ${{parent.outputs.register_metadata}}
