$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
# display_name: nyc_taxi_data_regression #usually better to leave this out tbh so you get unique names. 
experiment_name: nyc-taxi-pipeline-class
description: Train Classification model based on nyc taxi dataset

# <inputs_and_outputs>
inputs:
  model_name: 'taxi-classification'
  endpoint_name: 'demo-classification'
  deployment_name: 'green'
outputs: 
  pipeline_job_trained_model:
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
  pipeline_job_comparison:
    mode: rw_mount

# </inputs_and_outputs>

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster-uami
  continue_on_step_failure: false

jobs:
  merge_job:
    type: command
    code: ../src/merge_data
    command: >-
      python merge_data.py
      --raw_data_green ${{inputs.raw_data_green}}
      --raw_data_yellow ${{inputs.raw_data_yellow}}
      --merged_data ${{outputs.merged_data}}
    inputs:
      raw_data_green:
        type: uri_file 
        path: ../data/taxi-data/raw/greenTaxiData.csv
      raw_data_yellow:
        type: uri_file 
        path: ../data/taxi-data/raw/yellowTaxiData.csv
    outputs:
      merged_data:
        mode: upload
    environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest

  transform_job:
    type: command
    component: ../src/components/transform.yaml
    inputs:
      test_split_ratio: 0.3
      clean_data: ${{parent.jobs.merge_job.outputs.merged_data}}
    outputs:
      train_data:
      test_data: 

  train_job:
    type: command
    component: ../src/components/train.yaml
    inputs:
      training_data: ${{parent.jobs.transform_job.outputs.train_data}}
      testing_data: ${{parent.jobs.transform_job.outputs.test_data}}
      model_name: ${{parent.inputs.model_name}}
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}

  predict_job:
    type: command
    component: ../src/components/predict.yaml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
      test_data: ${{parent.jobs.transform_job.outputs.test_data}}
    outputs:
      predictions: ${{parent.outputs.pipeline_job_predictions}}

  compare_job:
    type: command
    component: ../src/components/compare.yaml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
      test_data: ${{parent.jobs.transform_job.outputs.test_data}}
      predictions: ${{parent.jobs.predict_job.outputs.predictions}}
      model_name: ${{parent.inputs.model_name}}
    outputs:
      compare_output: ${{parent.outputs.pipeline_job_comparison}}
    
  score_job:
    type: command
    component: ../src/components/score.yaml
    inputs:
      predictions: ${{parent.jobs.predict_job.outputs.predictions}}
      model: ${{parent.jobs.train_job.outputs.model_output}}
    outputs:
      score_report: ${{parent.outputs.pipeline_job_score_report}}

  registerws_job:
    type: command
    component: ../src/components/register.yaml
    inputs:
      model_input: ${{parent.jobs.train_job.outputs.model_output}}
      model_name: ${{parent.inputs.model_name}}
      compare_output: ${{parent.jobs.compare_job.outputs.compare_output}}
    outputs:
      register_output:
  
  deployws_job:
    type: command
    component: ../src/components/deploy.yaml
    inputs:
      model_name: ${{parent.inputs.model_name}}
      endpoint_name: ${{parent.inputs.endpoint_name}}
      deployment_name: ${{parent.inputs.deployment_name}}
      register_job_status: ${{parent.jobs.registerws_job.outputs.register_output}}