name: pydata-example
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pip=22.1.2
  - numpy~=1.22.3
  - pandas~=1.3.5
  - py-xgboost=1.3.3
  - pyopenssl=24.0.0
  - cryptography=42.0.2
  - 'psutil>=5.2.2,<6.0.0'
  - tqdm
  - setuptools=65.5.1
  - wheel=0.38.1
  - openssl=3.0.13
  - pip:
    - inference-schema
    - azureml-core==1.55.0.post2
    - azureml-mlflow==1.55.0
    - azureml-pipeline-core==1.55.0
    - azureml-telemetry==1.55.0
    - azureml-interpret==1.55.0
    - azureml-responsibleai==1.55.0
    - azureml-automl-core==1.55.0.post2
    - azureml-automl-runtime==1.55.0.post1
    - azureml-train-automl-client==1.55.0
    - azureml-train-automl-runtime==1.55.0.post1
    - azureml-train-automl==1.55.0
    - azureml-dataset-runtime==1.55.0
    - azureml-defaults==1.55.0
    - mlflow-skinny==2.9.2
    - torch==1.13.1
    - xgboost==1.3.3
    - prophet==1.1.4
    - inference-schema
    - mltable>=1.0.0
    - azure-identity
    - azure-ai-ml
    - azureml-inference-server-http==1.0.0
    - joblib~=1.2.0
    - cryptography>=42.0.4
    - certifi >= 2023.07.22
    - requests >= 2.31.0  
