name: h2o-binary-online
channels:
  - conda-forge
dependencies:
  - python=3.12
  - openjdk=17
  - pip
  - pip:
      - azureml-inference-server-http==1.4.1
      - h2o==3.46.0.12
      - numpy==1.26.4
      - pandas==2.2.3
